### PR TITLE
Make the use of V3 api the default

### PR DESCRIPTION
**Pull request by fridrich**
All SRG/SSR tv play web-sites use V3 api. Tried with SRF, RTS, RSI and even RTR.
For Radio, one has to set the v3 url to none. Will submit pull requests for that to rtsplayradio and srfplayradio too

### CODE REVIEW

**Comment by Flo3561** [comment]
@goggle: Could you have a look through this PR as the maintainer of this repository? It seems that the Kodi matrix build check failed. But the logs are too old and no more visible.
@claudep has offered his help to support as well.

**Comment by claudep** [comment]
@goggle, please just tell us if you don't have time or motivation for this module any longer. We can surely understand that! In that case, it would be great to transfer the repository to somewhere else.

**Comment by claudep** [comment]
Is it time to talk about a fork?

**Comment by Flo3561** [comment]
> Is it time to talk about a fork?

Would appreciate if this work on that Kodi module would continue.

**Comment by gaudenz** [comment]
Thanks for this patch. It makes the SRF Play Add-On mostly work again. One thing that still does not work is listing latest media by topic. Other similar listings like most viewed media by topic still work.

**Comment by goggle** [comment]
@fridrich Thanks for this! Sorry that it took so long, but all the changes regarding the APIv3 have been implemented in the master branch. Live TV is not supported though, but I don't know if I really want to include this in this plugin (there is the excellent `pvr.zattoo` for this). The pull requests to get the new releases into the official `matrix` addon repository are currently pending.

**Pull request closed without merging**
